const food = [
  {
    id: 1,
    type: "demo_img",
    name: "Product 1",
    description: "Description for Product 1.",
    price: 19.99,
    image: "image/slide_img/01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 2,
    type: "demo_img",
    name: "Product 2",
    description: "Description for Product 2.",
    price: 29.99,
    image: "/image/",
    style_h: 40,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 3,
    type: "demo_img",
    name: "Product 3",
    description: "Description for Product 3.",
    price: 29.99,
    image: "/image/slide_img/03.jpeg",
    style_h: 40,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 4,
    type: "dal",
    name: "Safe Rides",
    description: "Your safety is our priority. From sanitizing all bikes before every use, to extensive on-ground safety measures, your rides with ONN will always be safe and reliable. We also offer helmets on-demand.",
    price: 29.99,
    image: "/image/light_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 5,
    type: "dal",
    name: "Flexible Ownership",
    description: "Enjoy the freedom of owning a two-wheeler without the hefty down-payments, EMIs and paperwork. Now choose from rent-to-own, monthly/quarterly bookings, and even daily plans.",
    price: 29.99,
    image: "/image/mcb_01.jpeg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 6,
    type: "millet",
    name: "Smarter Mobility",
    description: "With your trusty ONN app, you can choose any bike, make instant payments, get offers, and manage all aspect of your ONN experience right from the comfort and ease of your mobile app.",
    price: 29.99,
    image: "/image/drone_01.jpeg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 7,
    type: "millet",
    name: "ONN Stations",
    description: "Your local ONN Station is here to make ensure your two-wheeler experience is flawless. At your neighborhood station, you get to pick any bike, get maintenance, sanitized, and a lot more.",
    price: 29.99,
    image: "/image/motor_01.jpeg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
  {
    id: 8,
    type:"wheat",
    name: "Topic",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore, doloribus, dolor ex sit illo nihil quod, numquam maxime illum ad hic explicabo blanditiis magnam architecto. Labore nihil cupiditate placeat exercitationem.",
    price: 29.99,
    image: "/image/battery_01.jpg",
    style_h: 70,
    style_w: 20,
    link: "/pi",
  },
];

const service_data = [
  {
    id: 1,
    name: "membership",
  },
  {
    id: 2,
    name: "subscription",
  },
  {
    id: 2,
    name: "join our community",
  },
  {
    id: 2,
    name: "funancial services",
  },
];

export {food,service_data};